import fs from "fs/promises";
import path from "path";
import matter from "gray-matter";
import slugify from "slugify";
import readingTime from "reading-time";

const postsDirectory = path.join(process.cwd(), "blog");
const outputPath = path.join(process.cwd(), "src/lib/posts.data.ts");

async function generatePostsData() {
  const fileNames = await fs.readdir(postsDirectory);

  const posts = await Promise.all(
    fileNames.map(async (fileName) => {
      const fullPath = path.join(postsDirectory, fileName);
      const fileContents = await fs.readFile(fullPath, "utf8");
      const { data: frontmatter, content } = matter(fileContents);

      return {
        slug: slugify(frontmatter.title, { lower: true, strict: true }),
        frontmatter,
        content,
        readingTime: readingTime(content),
      };
    })
  );

  const fileContents = `${[
    "// This file is auto-generated by scripts/generate-posts-data.ts",
    "// Do not edit manually.",
    "",
    `export const postsData = ${JSON.stringify(posts, null, 2)};`,
    "",
  ].join("\n")}`;

  await fs.writeFile(outputPath, fileContents, "utf8");
}

generatePostsData().catch((error) => {
  console.error("Failed to generate posts data", error);
  process.exit(1);
});
